version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: nome_do_banco_de_dados
    ports:
      - "5432:5432"
